"""Generate the on-screen keyboard layouts from the NiDA key table.

    python3 tools/gen_soft_keyboard.py

Writes res/xml/soft_khmer.xml, soft_khmer_shift.xml, soft_latin.xml and
soft_latin_shift.xml. The Khmer layers come from tools/nida_layout.json, the
same table the physical .kcm is generated from, so the on-screen keys sit where
the physical ones do and the five two-code-point vowels are typed in full here
too (via android:keyOutputText, which a key character map has no equivalent of).
"""

import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
NIDA = json.load(open(os.path.join(HERE, 'nida_layout.json'), encoding='utf-8'))

# Keys are named by the physical key they correspond to, row by row. Every
# printing key of the physical layout appears, so nothing typeable on the
# physical keyboard is missing on screen.
# The number row is part of the letter layers, not tucked behind ?123. On a
# NiDA keyboard it is not a number row at all: it carries Khmer digits on the
# base layer and vowel signs and punctuation on the shift layer, so hiding it
# hid characters that ordinary Khmer needs. Thirteen keys across is no narrower
# than the QWERTY row directly below it, which is also thirteen.
NUMBER_ROW = ['GRAVE', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0',
              'MINUS', 'EQUALS']

ROWS = [
    NUMBER_ROW,
    ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P',
     'LEFT_BRACKET', 'RIGHT_BRACKET', 'BACKSLASH'],
    ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'SEMICOLON', 'APOSTROPHE'],
    ['Z', 'X', 'C', 'V', 'B', 'N', 'M', 'COMMA', 'PERIOD', 'SLASH'],
]

LATIN_NUMBER_ROW = {
    'base':  ['`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '='],
    'shift': ['~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+'],
}

LATIN = {
    'base': [
        LATIN_NUMBER_ROW['base'],
        ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\\'],
        ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', "'"],
        ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/'],
    ],
    'shift': [
        LATIN_NUMBER_ROW['shift'],
        ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '{', '}', '|'],
        ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ':', '"'],
        ['Z', 'X', 'C', 'V', 'B', 'N', 'M', '<', '>', '?'],
    ],
}

# android.inputmethodservice.Keyboard constants.
KEYCODE_SHIFT, KEYCODE_MODE_CHANGE, KEYCODE_DONE, KEYCODE_DELETE = -1, -2, -4, -5

# Ours, for moving between the letter layers and the symbols page.
KEYCODE_TO_SYMBOLS = -101
KEYCODE_TO_LETTERS = -102

# Every page is this tall in total, so the keyboard does not jump in size when
# one is swapped for another, and each page divides it by however many rows it
# has. Five rows of letters at 50dp would have been a third of a phone screen;
# this keeps the whole keyboard to about what four rows used to take.
TOTAL_HEIGHT = 224.0

def header(rows):
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by tools/gen_soft_keyboard.py - do not edit by hand. -->\n'
            '<Keyboard xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:keyWidth="10%%p"\n'
            '    android:keyHeight="%.0fdp"\n'
            '    android:horizontalGap="0px"\n'
            '    android:verticalGap="0px">\n' % (TOTAL_HEIGHT / rows))

def esc(text):
    out = (text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
               .replace('"', '&quot;').replace("'", "\\'"))
    # aapt reads a leading @ as a resource reference and ? as a theme attribute.
    if out[:1] in ('@', '?'):
        out = '\\' + out
    return out

def key(label, width=None, extra=''):
    """A key that types `label`, which may be more than one code point."""
    attrs = ['android:codes="%d"' % ord(label[0]), 'android:keyLabel="%s"' % esc(label)]
    if len(label) > 1:
        attrs.append('android:keyOutputText="%s"' % esc(label))
    if width:
        attrs.append('android:keyWidth="%s"' % width)
    if extra:
        attrs.append(extra)
    return '        <Key %s />\n' % ' '.join(attrs)

def special(code, label, width, extra=''):
    attrs = ['android:codes="%d"' % code, 'android:keyLabel="%s"' % esc(label),
             'android:keyWidth="%s"' % width]
    if extra:
        attrs.append(extra)
    return '        <Key %s />\n' % ' '.join(attrs)

SHIFT_WIDTH = 12.0      # per cent of the row width, for shift and backspace


def build(rows, language_label):
    out = [header(len(rows) + 1)]       # the rows given, plus the function row

    # Rows differ in length, so share each row's width out across its own keys.
    # Leaving this to the keyboard-level default silently overflows: 13 keys at
    # the default 10%p is 130% of the screen, and the last keys render off the
    # right edge where they cannot be typed.
    for row in rows[:-1]:
        width = '%.2f%%p' % (100.0 / len(row))
        out.append('    <Row>\n')
        for label in row:
            out.append(key(label, width=width))
        out.append('    </Row>\n')

    # Bottom letter row, wrapped by shift and backspace.
    width = '%.2f%%p' % ((100.0 - 2 * SHIFT_WIDTH) / len(rows[-1]))
    out.append('    <Row>\n')
    out.append(special(KEYCODE_SHIFT, '\u21e7', '%.2f%%p' % SHIFT_WIDTH,
                       'android:isModifier="true" android:isSticky="true"'))
    for label in rows[-1]:
        out.append(key(label, width=width))
    out.append(special(KEYCODE_DELETE, '\u232b', '%.2f%%p' % SHIFT_WIDTH,
                       'android:isRepeatable="true"'))
    out.append('    </Row>\n')

    # Function row.
    out.append('    <Row android:rowEdgeFlags="bottom">\n')
    out.append(special(KEYCODE_TO_SYMBOLS, '?123', '18%p'))
    out.append(special(KEYCODE_MODE_CHANGE, language_label, '18%p'))
    out.append(key(' ', width='40%p'))
    out.append(special(KEYCODE_DONE, '\u23ce', '24%p'))
    out.append('    </Row>\n')

    out.append('</Keyboard>\n')
    body = ''.join(out)
    check_rows_fit(body)
    return body


def check_rows_fit(body):
    """Every row must total at most 100% of the screen, or keys fall off it."""
    for number, row in enumerate(re.findall(r'<Row[^>]*>(.*?)</Row>', body, re.S), 1):
        widths = re.findall(r'keyWidth="([\d.]+)%p"', row)
        keys = len(re.findall(r'<Key ', row))
        if len(widths) != keys:
            raise AssertionError('row %d: %d keys but %d have an explicit width; '
                                 'the rest fall back to the keyboard default'
                                 % (number, keys, len(widths)))
        total = sum(float(w) for w in widths)
        if total > 100.5:
            raise AssertionError('row %d: keys total %.2f%% of the screen width'
                                 % (number, total))


def build_symbols(base_row, shift_row, letters_label):
    """The page behind ?123: punctuation and symbols, plus a way back.

    The number row has thirteen keys, and thirteen keys across a screen are
    about 7% wide each - narrower than a fingertip, which is what "need bigger
    key" was about. The digits are what this page is reached for, so they get a
    row of ten to themselves at the full 10% each, their shifted symbols get
    the next row, and the six keys either side of the digits (` - = and their
    shifted forms) share a third row at better than 13% each.
    """
    # Index 0 is `, 1..10 are the digits 1-0, 11 and 12 are - and =.
    digits, shifted_digits = base_row[1:11], shift_row[1:11]
    edges = [base_row[0], base_row[11], base_row[12],
             shift_row[0], shift_row[11], shift_row[12]]

    out = [header(4)]
    for row in (digits, shifted_digits):
        width = '%.2f%%p' % (100.0 / len(row))
        out.append('    <Row>\n')
        for label in row:
            out.append(key(label, width=width))
        out.append('    </Row>\n')

    # Backspace rides this row so the bottom row can give space more room.
    width = '%.2f%%p' % ((100.0 - SHIFT_WIDTH) / len(edges))
    out.append('    <Row>\n')
    for label in edges:
        out.append(key(label, width=width))
    out.append(special(KEYCODE_DELETE, '\u232b', '%.2f%%p' % SHIFT_WIDTH,
                       'android:isRepeatable="true"'))
    out.append('    </Row>\n')

    out.append('    <Row android:rowEdgeFlags="bottom">\n')
    out.append(special(KEYCODE_TO_LETTERS, letters_label, '20%p'))
    out.append(key(' ', width='52%p'))
    out.append(special(KEYCODE_DONE, '\u23ce', '28%p'))
    out.append('    </Row>\n')
    out.append('</Keyboard>\n')
    body = ''.join(out)
    check_rows_fit(body)
    return body


def build_number():
    """The pad a field asking for digits gets, whatever the language."""
    out = [header(4)]
    for row in (['1', '2', '3'], ['4', '5', '6'], ['7', '8', '9']):
        out.append('    <Row>\n')
        for label in row:
            out.append(key(label, width='33.33%p'))
        out.append('    </Row>\n')
    out.append('    <Row android:rowEdgeFlags="bottom">\n')
    out.append(key('.', width='16.66%p'))
    out.append(key('0', width='33.33%p'))
    out.append(key('-', width='16.66%p'))
    out.append(special(KEYCODE_DELETE, '\u232b', '16.66%p',
                       'android:isRepeatable="true"'))
    out.append(special(KEYCODE_DONE, '\u23ce', '16.66%p'))
    out.append('    </Row>\n')
    out.append('</Keyboard>\n')
    body = ''.join(out)
    check_rows_fit(body)
    return body


def khmer_rows(layer):
    rows = []
    for row in ROWS:
        built = []
        for name in row:
            value = NIDA[name].get(layer) or NIDA[name]['base']
            built.append(value)
        rows.append(built)
    return rows

KHMER_LABEL = 'ខ្មែរ'

targets = {
    'soft_khmer.xml':       build(khmer_rows('base'),  'ABC'),
    'soft_khmer_shift.xml': build(khmer_rows('shift'), 'ABC'),
    'soft_latin.xml':       build(LATIN['base'],  KHMER_LABEL),
    'soft_latin_shift.xml': build(LATIN['shift'], KHMER_LABEL),
    'soft_khmer_sym.xml':   build_symbols(
        [NIDA[k]['base'] for k in NUMBER_ROW],
        [NIDA[k].get('shift') or NIDA[k]['base'] for k in NUMBER_ROW],
        KHMER_LABEL),
    'soft_latin_sym.xml':   build_symbols(
        LATIN_NUMBER_ROW['base'], LATIN_NUMBER_ROW['shift'], 'ABC'),
    'soft_number.xml':      build_number(),
}
for name, body in targets.items():
    open(os.path.join(ROOT, 'app/src/main/res/xml', name), 'w', encoding='utf-8').write(body)
    print('wrote res/xml/%s' % name)

multi = [(n, v) for n in NIDA for l in ('base', 'shift')
         for v in [NIDA[n].get(l)] if v and len(v) > 1]
print('\ntwo-code-point keys carried onto the on-screen keyboard: %d' % len(multi))
for n, v in sorted(set(multi)):
    print('   %-10s %s  %s' % (n, v, ' '.join('U+%04X' % ord(c) for c in v)))
