"""Generate the on-screen keyboard layouts from the NiDA key table.

    python3 tools/gen_soft_keyboard.py

Writes res/xml/soft_khmer.xml, soft_khmer_shift.xml, soft_latin.xml and
soft_latin_shift.xml. The Khmer layers come from tools/nida_layout.json, the
same table the physical .kcm is generated from, so the on-screen keys sit where
the physical ones do and the five two-code-point vowels are typed in full here
too (via android:keyOutputText, which a key character map has no equivalent of).
"""

import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
NIDA = json.load(open(os.path.join(HERE, 'nida_layout.json'), encoding='utf-8'))

# Keys are named by the physical key they correspond to, row by row. Every
# printing key of the physical layout appears, so nothing typeable on the
# physical keyboard is missing on screen.
# The number row is part of the letter layers, not tucked behind ?123. On a
# NiDA keyboard it is not a number row at all: it carries Khmer digits on the
# base layer and vowel signs and punctuation on the shift layer, so hiding it
# hid characters that ordinary Khmer needs. Thirteen keys across is no narrower
# than the QWERTY row directly below it, which is also thirteen.
NUMBER_ROW = ['GRAVE', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0',
              'MINUS', 'EQUALS']

ROWS = [
    NUMBER_ROW,
    ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P',
     'LEFT_BRACKET', 'RIGHT_BRACKET', 'BACKSLASH'],
    ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'SEMICOLON', 'APOSTROPHE'],
    ['Z', 'X', 'C', 'V', 'B', 'N', 'M', 'COMMA', 'PERIOD', 'SLASH'],
]

LATIN_NUMBER_ROW = {
    'base':  ['`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '='],
    'shift': ['~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+'],
}

# The phone-portrait Latin layers, in the shape every phone keyboard uses:
# ten keys, nine, then seven between shift and backspace with the comma and
# full stop beside them. The number row and the outer punctuation columns come
# off, which is what buys the width - every one of them is on the ?123 page.
#
# There is no Khmer equivalent of this list, and that is not an oversight. On a
# NiDA keyboard the columns a phone keyboard drops are not punctuation: the
# apostrophe key is ់, the semicolon key is ើ, the full stop key is ។, the
# bracket keys are ៀ ឿ ឪ ឧ. Every position carries a letter of the language, so
# Khmer cannot be narrowed to ten columns without taking characters away. Khmer
# portrait gets the shorter keys and keeps all of them.
LATIN_COMPACT = {
    'base': [
        ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
        ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l'],
        ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.'],
    ],
    'shift': [
        ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
        ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'],
        ['Z', 'X', 'C', 'V', 'B', 'N', 'M', '<', '>'],
    ],
}

# What the compact layers leave behind, and where it goes instead.
LATIN_DISPLACED = {
    'base':  ['`', '-', '=', '[', ']', '\\', ';', "'", '/'],
    'shift': ['~', '_', '+', '{', '}', '|', ':', '"', '?'],
}

LATIN = {
    'base': [
        LATIN_NUMBER_ROW['base'],
        ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\\'],
        ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', "'"],
        ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/'],
    ],
    'shift': [
        LATIN_NUMBER_ROW['shift'],
        ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '{', '}', '|'],
        ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ':', '"'],
        ['Z', 'X', 'C', 'V', 'B', 'N', 'M', '<', '>', '?'],
    ],
}

# android.inputmethodservice.Keyboard constants.
KEYCODE_SHIFT, KEYCODE_MODE_CHANGE, KEYCODE_DONE, KEYCODE_DELETE = -1, -2, -4, -5

# Ours, for moving between the letter layers and the symbols page, and to the
# emoji grid - which is not a Keyboard at all, so the service swaps the view.
KEYCODE_TO_SYMBOLS = -101
KEYCODE_TO_LETTERS = -102
KEYCODE_TO_EMOJI = -103

# Every page is this tall in total, so the keyboard does not jump in size when
# one is swapped for another, and each page divides it by however many rows it
# has. Five rows of letters at 50dp would have been a third of a phone screen;
# this keeps the whole keyboard to about what four rows used to take.
TOTAL_HEIGHT = 224.0


def header(rows):
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by tools/gen_soft_keyboard.py - do not edit by hand. -->\n'
            '<Keyboard xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:keyWidth="10%%p"\n'
            '    android:keyHeight="%.0fdp"\n'
            '    android:horizontalGap="0px"\n'
            '    android:verticalGap="0px">\n' % (TOTAL_HEIGHT / rows))

def esc(text):
    out = (text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
               .replace('"', '&quot;').replace("'", "\\'"))
    # aapt reads a leading @ as a resource reference and ? as a theme attribute.
    if out[:1] in ('@', '?'):
        out = '\\' + out
    return out

# Characters with nothing to draw. They are real Khmer typing - a zero width
# joiner or non-joiner decides whether a cluster stacks - but a key showing
# them would be a blank key, so these are named instead. KeyboardView draws a
# label of more than one character at its label size, which the keyboard
# layouts set to 12sp so that four letters fit across a key of this row's
# width; at the 14sp default "ZWNJ" runs over its neighbour.
INVISIBLE = {'\u200c': 'ZWNJ', '\u200d': 'ZWJ', '\u200b': 'ZWSP'}


def key(label, width=None, extra=''):
    """A key that types `label`, which may be more than one code point."""
    shown = INVISIBLE.get(label, label)
    attrs = ['android:codes="%d"' % ord(label[0]), 'android:keyLabel="%s"' % esc(shown)]
    if len(label) > 1 or shown != label:
        attrs.append('android:keyOutputText="%s"' % esc(label))
    if width:
        attrs.append('android:keyWidth="%s"' % width)
    if extra:
        attrs.append(extra)
    return '        <Key %s />\n' % ' '.join(attrs)

def special(code, label, width, extra=''):
    attrs = ['android:codes="%d"' % code, 'android:keyLabel="%s"' % esc(label),
             'android:keyWidth="%s"' % width]
    if extra:
        attrs.append(extra)
    return '        <Key %s />\n' % ' '.join(attrs)

SHIFT_WIDTH = 12.0      # per cent of the row width, for shift and backspace


def build(rows, language_label, other_page_label, compact=False):
    out = [header(len(rows) + 1)]       # the rows given, plus the function row

    # Rows differ in length, so share each row's width out across its own keys.
    # Leaving this to the keyboard-level default silently overflows: 13 keys at
    # the default 10%p is 130% of the screen, and the last keys render off the
    # right edge where they cannot be typed.
    for row in rows[:-1]:
        width = '%.2f%%p' % (100.0 / len(row))
        out.append('    <Row>\n')
        for label in row:
            out.append(key(label, width=width))
        out.append('    </Row>\n')

    # Bottom letter row. On a phone shift has moved down to the function row,
    # so the letters keep the width it used to take.
    taken = SHIFT_WIDTH if compact else 2 * SHIFT_WIDTH
    width = '%.2f%%p' % ((100.0 - taken) / len(rows[-1]))
    out.append('    <Row>\n')
    if not compact:
        out.append(special(KEYCODE_SHIFT, '\u21e7', '%.2f%%p' % SHIFT_WIDTH,
                           'android:isModifier="true" android:isSticky="true"'))
    for label in rows[-1]:
        out.append(key(label, width=width))
    out.append(special(KEYCODE_DELETE, '\u232b', '%.2f%%p' % SHIFT_WIDTH,
                       'android:isRepeatable="true"'))
    out.append('    </Row>\n')

    # Function row.
    out.append(function_row(other_page_label, language_label, compact))

    out.append('</Keyboard>\n')
    body = ''.join(out)
    check_rows_fit(body)
    return body


def function_row(other_page_label, language_label, compact=False):
    """The bottom row of a letter layer.

    Emoji get a key of their own here rather than a long press on the space
    bar, which is where most keyboards hide them: a key that is only found by
    holding another key down is a key most people never find.

    On a phone shift takes the slot the language key had, and the language is
    changed by sliding across the space bar instead. The space bar is labelled
    with the script it is currently typing, so the slide has something to point
    at - an unlabelled key with a hidden gesture would be the same mistake as
    hiding emoji behind a long press.
    """
    out = ['    <Row android:rowEdgeFlags="bottom">\n']
    out.append(special(KEYCODE_TO_SYMBOLS, other_page_label, '15%p'))
    if compact:
        out.append(special(KEYCODE_SHIFT, '\u21e7', '15%p',
                           'android:isModifier="true" android:isSticky="true"'))
    else:
        out.append(special(KEYCODE_MODE_CHANGE, language_label, '15%p'))
    out.append(key(' ', width='37%p'))
    out.append(special(KEYCODE_TO_EMOJI, '\U0001f642', '13%p'))
    out.append(special(KEYCODE_DONE, '\u23ce', '20%p'))
    out.append('    </Row>\n')
    return ''.join(out)


def check_rows_fit(body):
    """Every row must total at most 100% of the screen, or keys fall off it."""
    for number, row in enumerate(re.findall(r'<Row[^>]*>(.*?)</Row>', body, re.S), 1):
        widths = re.findall(r'keyWidth="([\d.]+)%p"', row)
        keys = len(re.findall(r'<Key ', row))
        if len(widths) != keys:
            raise AssertionError('row %d: %d keys but %d have an explicit width; '
                                 'the rest fall back to the keyboard default'
                                 % (number, keys, len(widths)))
        total = sum(float(w) for w in widths)
        if total > 100.5:
            raise AssertionError('row %d: keys total %.2f%% of the screen width'
                                 % (number, total))


def build_symbols(base_row, shift_row, letters_label, displaced=None):
    """The page behind ?123: punctuation and symbols, plus a way back.

    The number row has thirteen keys, and thirteen keys across a screen are
    about 7% wide each - narrower than a fingertip, which is what "need bigger
    key" was about. The digits are what this page is reached for, so they get a
    row of ten to themselves at the full 10% each, their shifted symbols get
    the next row, and the six keys either side of the digits (` - = and their
    shifted forms) share a third row at better than 13% each.
    """
    # Index 0 is `, 1..10 are the digits 1-0, 11 and 12 are - and =.
    digits, shifted_digits = base_row[1:11], shift_row[1:11]
    edges = [base_row[0], base_row[11], base_row[12],
             shift_row[0], shift_row[11], shift_row[12]]

    rows = 4 if displaced is None else 5
    out = [header(rows)]
    for row in (digits, shifted_digits):
        width = '%.2f%%p' % (100.0 / len(row))
        out.append('    <Row>\n')
        for label in row:
            out.append(key(label, width=width))
        out.append('    </Row>\n')

    if displaced is not None:
        # The keys the compact letter layers dropped. Backspace rides the first
        # of the two rows, so the bottom row can give the space bar more room.
        width = '%.2f%%p' % ((100.0 - SHIFT_WIDTH) / len(displaced['base']))
        out.append('    <Row>\n')
        for label in displaced['base']:
            out.append(key(label, width=width))
        out.append(special(KEYCODE_DELETE, '\u232b', '%.2f%%p' % SHIFT_WIDTH,
                           'android:isRepeatable="true"'))
        out.append('    </Row>\n')
        width = '%.2f%%p' % (100.0 / len(displaced['shift']))
        out.append('    <Row>\n')
        for label in displaced['shift']:
            out.append(key(label, width=width))
        out.append('    </Row>\n')
    else:
        # Backspace rides this row so the bottom row can give space more room.
        width = '%.2f%%p' % ((100.0 - SHIFT_WIDTH) / len(edges))
        out.append('    <Row>\n')
        for label in edges:
            out.append(key(label, width=width))
        out.append(special(KEYCODE_DELETE, '\u232b', '%.2f%%p' % SHIFT_WIDTH,
                           'android:isRepeatable="true"'))
        out.append('    </Row>\n')

    out.append('    <Row android:rowEdgeFlags="bottom">\n')
    out.append(special(KEYCODE_TO_LETTERS, letters_label, '20%p'))
    out.append(key(' ', width='52%p'))
    out.append(special(KEYCODE_DONE, '\u23ce', '28%p'))
    out.append('    </Row>\n')
    out.append('</Keyboard>\n')
    body = ''.join(out)
    check_rows_fit(body)
    return body


def build_number():
    """The pad a field asking for digits gets, whatever the language."""
    out = [header(4)]
    for row in (['1', '2', '3'], ['4', '5', '6'], ['7', '8', '9']):
        out.append('    <Row>\n')
        for label in row:
            out.append(key(label, width='33.33%p'))
        out.append('    </Row>\n')
    out.append('    <Row android:rowEdgeFlags="bottom">\n')
    out.append(key('.', width='16.66%p'))
    out.append(key('0', width='33.33%p'))
    out.append(key('-', width='16.66%p'))
    out.append(special(KEYCODE_DELETE, '\u232b', '16.66%p',
                       'android:isRepeatable="true"'))
    out.append(special(KEYCODE_DONE, '\u23ce', '16.66%p'))
    out.append('    </Row>\n')
    out.append('</Keyboard>\n')
    body = ''.join(out)
    check_rows_fit(body)
    return body


def build_alt(rows, letters_label):
    """The Khmer page behind ?123: the layout's AltGr layer.

    A NiDA keyboard has four layers, and the third one - reached with the right
    Alt key on a physical keyboard - is where the independent vowels live (ឯ ឫ
    ឱ ឰ ឳ ឦ ឨ ឩ), along with the Khmer punctuation signs (៖ ៈ ៎ ៑ ៙ ៚ ៘ ៓ ៝),
    the currency signs and the whole of Latin punctuation. None of it was
    reachable on screen at all, which made perfectly ordinary Khmer impossible
    to type without a physical keyboard.

    This is why ?123 shows this page rather than a symbols page under Khmer:
    the digits are back on the number row where NiDA puts them, and this layer
    carries the punctuation a symbols page would have duplicated.

    The fourth layer, shift+AltGr, is the lunar date and divination symbols
    (U+19E0..U+19FF). They are rare enough that most fonts have no glyph for
    them, so they are left to the physical keyboard.
    """
    out = [header(len(rows) + 1)]
    for row in rows[:-1]:
        width = '%.2f%%p' % (100.0 / len(row))
        out.append('    <Row>\n')
        for label in row:
            out.append(key(label, width=width))
        out.append('    </Row>\n')

    # No shift key: there is no page for it to lead to.
    width = '%.2f%%p' % ((100.0 - SHIFT_WIDTH) / len(rows[-1]))
    out.append('    <Row>\n')
    for label in rows[-1]:
        out.append(key(label, width=width))
    out.append(special(KEYCODE_DELETE, '\u232b', '%.2f%%p' % SHIFT_WIDTH,
                       'android:isRepeatable="true"'))
    out.append('    </Row>\n')

    out.append('    <Row android:rowEdgeFlags="bottom">\n')
    out.append(special(KEYCODE_TO_LETTERS, letters_label, '20%p'))
    out.append(key(' ', width='52%p'))
    out.append(special(KEYCODE_DONE, '\u23ce', '28%p'))
    out.append('    </Row>\n')
    out.append('</Keyboard>\n')
    body = ''.join(out)
    check_rows_fit(body)
    return body


def khmer_rows(layer):
    rows = []
    for row in ROWS:
        built = []
        for name in row:
            value = NIDA[name].get(layer) or NIDA[name]['base']
            built.append(value)
        rows.append(built)
    return rows

KHMER_LABEL = 'ខ្មែរ'


def layouts(compact):
    """Every page of the keyboard, in one of its two shapes."""
    latin = LATIN_COMPACT if compact else LATIN
    displaced = LATIN_DISPLACED if compact else None
    return {
        # Under Khmer that key opens the layout's AltGr layer, not a numbers
        # page - the digits are on the number row - so it says what it does.
        'soft_khmer.xml':       build(khmer_rows('base'),  'ABC', 'Alt', compact),
        'soft_khmer_shift.xml': build(khmer_rows('shift'), 'ABC', 'Alt', compact),
        'soft_latin.xml':       build(latin['base'],  KHMER_LABEL, '?123', compact),
        'soft_latin_shift.xml': build(latin['shift'], KHMER_LABEL, '?123', compact),
        'soft_khmer_alt.xml':   build_alt(khmer_rows('ralt'), KHMER_LABEL),
        'soft_latin_sym.xml':   build_symbols(
            LATIN_NUMBER_ROW['base'], LATIN_NUMBER_ROW['shift'], 'ABC',
            displaced),
        'soft_number.xml':      build_number(),
    }


# How the keyboard is shaped on each kind of screen. The resource qualifiers do
# the choosing: a phone held upright gets the unqualified set, anything in
# landscape gets -land, and a tablet gets -sw600dp in either orientation
# (a screen qualifier outranks an orientation one, so a tablet in landscape
# lands there too - both are the full layout, so it makes no difference).
#
# A phone held upright is the only screen with no room to spare, so it is the
# only one that gives anything up.
VARIANTS = [
    dict(xml='xml',          values='values',          compact=True,
         height=190.0, strip=36.0, text=15.0, pad=10.0),
    # A phone on its side has less height, not more, so landscape is the
    # compact layout too - shorter still, and wider keys for free.
    dict(xml='xml-land',     values='values-land',     compact=True,
         height=160.0, strip=32.0, text=14.0, pad=10.0),
    dict(xml='xml-sw600dp',  values='values-sw600dp',  compact=False,
         height=240.0, strip=48.0, text=18.0, pad=16.0),
]

DIMENS = ('<?xml version="1.0" encoding="utf-8"?>\n'
          '<!-- Generated by tools/gen_soft_keyboard.py - do not edit by hand. -->\n'
          '<resources>\n'
          '    <!-- Every page of the keyboard is this tall, the emoji grid too. -->\n'
          '    <dimen name="keyboard_height">%(height).0fdp</dimen>\n'
          '    <dimen name="suggestion_height">%(strip).0fdp</dimen>\n'
          '    <dimen name="suggestion_text">%(text).0fsp</dimen>\n'
          '    <dimen name="suggestion_pad">%(pad).0fdp</dimen>\n'
          '</resources>\n')

for variant in VARIANTS:
    TOTAL_HEIGHT = variant['height']
    xml_dir = os.path.join(ROOT, 'app/src/main/res', variant['xml'])
    values_dir = os.path.join(ROOT, 'app/src/main/res', variant['values'])
    os.makedirs(xml_dir, exist_ok=True)
    os.makedirs(values_dir, exist_ok=True)
    for name, body in layouts(variant['compact']).items():
        open(os.path.join(xml_dir, name), 'w', encoding='utf-8').write(body)
    open(os.path.join(values_dir, 'dimens.xml'), 'w', encoding='utf-8').write(
        DIMENS % variant)
    print('wrote res/%-14s %d pages, %s, %.0fdp tall'
          % (variant['xml'], len(layouts(variant['compact'])),
             'compact' if variant['compact'] else 'full', variant['height']))

multi = [(n, v) for n in NIDA for l in ('base', 'shift')
         for v in [NIDA[n].get(l)] if v and len(v) > 1]
print('\ntwo-code-point keys carried onto the on-screen keyboard: %d' % len(multi))
for n, v in sorted(set(multi)):
    print('   %-10s %s  %s' % (n, v, ' '.join('U+%04X' % ord(c) for c in v)))
