"""Generate the on-screen keyboard layouts from the NiDA key table.

    python3 tools/gen_soft_keyboard.py

Writes res/xml/soft_khmer.xml, soft_khmer_shift.xml, soft_latin.xml and
soft_latin_shift.xml. The Khmer layers come from tools/nida_layout.json, the
same table the physical .kcm is generated from, so the on-screen keys sit where
the physical ones do and the five two-code-point vowels are typed in full here
too (via android:keyOutputText, which a key character map has no equivalent of).
"""

import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
NIDA = json.load(open(os.path.join(HERE, 'nida_layout.json'), encoding='utf-8'))

# Keys are named by the physical key they correspond to, row by row. Every
# printing key of the physical layout appears, so nothing typeable on the
# physical keyboard is missing on screen.
ROWS = [
    ['GRAVE', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', 'MINUS', 'EQUALS'],
    ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P',
     'LEFT_BRACKET', 'RIGHT_BRACKET', 'BACKSLASH'],
    ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'SEMICOLON', 'APOSTROPHE'],
    ['Z', 'X', 'C', 'V', 'B', 'N', 'M', 'COMMA', 'PERIOD', 'SLASH'],
]

LATIN = {
    'base': [
        ['`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '='],
        ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\\'],
        ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', "'"],
        ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/'],
    ],
    'shift': [
        ['~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+'],
        ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '{', '}', '|'],
        ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ':', '"'],
        ['Z', 'X', 'C', 'V', 'B', 'N', 'M', '<', '>', '?'],
    ],
}

# android.inputmethodservice.Keyboard constants.
KEYCODE_SHIFT, KEYCODE_MODE_CHANGE, KEYCODE_DONE, KEYCODE_DELETE = -1, -2, -4, -5

HEADER = ('<?xml version="1.0" encoding="utf-8"?>\n'
          '<!-- Generated by tools/gen_soft_keyboard.py - do not edit by hand. -->\n'
          '<Keyboard xmlns:android="http://schemas.android.com/apk/res/android"\n'
          '    android:keyWidth="10%p"\n'
          '    android:keyHeight="50dp"\n'
          '    android:horizontalGap="0px"\n'
          '    android:verticalGap="0px">\n')

def esc(text):
    out = (text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
               .replace('"', '&quot;').replace("'", "\\'"))
    # aapt reads a leading @ as a resource reference and ? as a theme attribute.
    if out[:1] in ('@', '?'):
        out = '\\' + out
    return out

def key(label, width=None, extra=''):
    """A key that types `label`, which may be more than one code point."""
    attrs = ['android:codes="%d"' % ord(label[0]), 'android:keyLabel="%s"' % esc(label)]
    if len(label) > 1:
        attrs.append('android:keyOutputText="%s"' % esc(label))
    if width:
        attrs.append('android:keyWidth="%s"' % width)
    if extra:
        attrs.append(extra)
    return '        <Key %s />\n' % ' '.join(attrs)

def special(code, label, width, extra=''):
    attrs = ['android:codes="%d"' % code, 'android:keyLabel="%s"' % esc(label),
             'android:keyWidth="%s"' % width]
    if extra:
        attrs.append(extra)
    return '        <Key %s />\n' % ' '.join(attrs)

SHIFT_WIDTH = 12.0      # per cent of the row width, for shift and backspace


def build(rows, language_label):
    out = [HEADER]

    # Rows differ in length, so share each row's width out across its own keys.
    # Leaving this to the keyboard-level default silently overflows: 13 keys at
    # the default 10%p is 130% of the screen, and the last keys render off the
    # right edge where they cannot be typed.
    for row in rows[:3]:
        width = '%.2f%%p' % (100.0 / len(row))
        out.append('    <Row>\n')
        for label in row:
            out.append(key(label, width=width))
        out.append('    </Row>\n')

    # Letters row, wrapped by shift and backspace.
    width = '%.2f%%p' % ((100.0 - 2 * SHIFT_WIDTH) / len(rows[3]))
    out.append('    <Row>\n')
    out.append(special(KEYCODE_SHIFT, '\u21e7', '%.2f%%p' % SHIFT_WIDTH,
                       'android:isModifier="true" android:isSticky="true"'))
    for label in rows[3]:
        out.append(key(label, width=width))
    out.append(special(KEYCODE_DELETE, '\u232b', '%.2f%%p' % SHIFT_WIDTH,
                       'android:isRepeatable="true"'))
    out.append('    </Row>\n')

    # Function row.
    out.append('    <Row android:rowEdgeFlags="bottom">\n')
    out.append(special(KEYCODE_MODE_CHANGE, language_label, '20%p'))
    out.append(key(' ', width='50%p'))
    out.append(special(KEYCODE_DONE, '\u23ce', '30%p'))
    out.append('    </Row>\n')

    out.append('</Keyboard>\n')
    body = ''.join(out)
    check_rows_fit(body)
    return body


def check_rows_fit(body):
    """Every row must total at most 100% of the screen, or keys fall off it."""
    for number, row in enumerate(re.findall(r'<Row[^>]*>(.*?)</Row>', body, re.S), 1):
        widths = re.findall(r'keyWidth="([\d.]+)%p"', row)
        keys = len(re.findall(r'<Key ', row))
        if len(widths) != keys:
            raise AssertionError('row %d: %d keys but %d have an explicit width; '
                                 'the rest fall back to the keyboard default'
                                 % (number, keys, len(widths)))
        total = sum(float(w) for w in widths)
        if total > 100.5:
            raise AssertionError('row %d: keys total %.2f%% of the screen width'
                                 % (number, total))


def khmer_rows(layer):
    rows = []
    for row in ROWS:
        built = []
        for name in row:
            value = NIDA[name].get(layer) or NIDA[name]['base']
            built.append(value)
        rows.append(built)
    return rows

targets = {
    'soft_khmer.xml':       build(khmer_rows('base'),  'ABC'),
    'soft_khmer_shift.xml': build(khmer_rows('shift'), 'ABC'),
    'soft_latin.xml':       build(LATIN['base'],  'ខ្មែរ'),
    'soft_latin_shift.xml': build(LATIN['shift'], 'ខ្មែរ'),
}
for name, body in targets.items():
    open(os.path.join(ROOT, 'app/src/main/res/xml', name), 'w', encoding='utf-8').write(body)
    print('wrote res/xml/%s' % name)

multi = [(n, v) for n in NIDA for l in ('base', 'shift')
         for v in [NIDA[n].get(l)] if v and len(v) > 1]
print('\ntwo-code-point keys carried onto the on-screen keyboard: %d' % len(multi))
for n, v in sorted(set(multi)):
    print('   %-10s %s  %s' % (n, v, ' '.join('U+%04X' % ord(c) for c in v)))
